name: Build and deploy To-Do Backend to Azure

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '7.x'

      - name: Build project
        run: dotnet build --configuration Release

      - name: Publish
        run: dotnet publish ./ToDo.API/ToDo.API.csproj -c Release -o ${{env.DOTNET_ROOT}}/ToDo-Backend

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: .ToDo-Backend
          path: ${{env.DOTNET_ROOT}}/ToDo-Backend

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: .ToDo-Backend

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'agreyddous-to-do-backend'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_00AA697C686C4460A298ACD837324115 }}
          package: .
